name: CI

permissions: {}

on:
  pull_request:
  push:
    branches:
      - alpha
      - beta
      - main
      - renovate/**

jobs:
  ci-optimization:
    name: CI optimization
    uses: dargmuesli/github-actions/.github/workflows/ci-optimization.yml@7a088e5faf37b7992867f40fc1c17efa954d8c52 # 5.9.6
    permissions:
      pull-requests: read
  build:
    needs: ci-optimization
    if: needs.ci-optimization.outputs.continue == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Set up JDK
      uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
      with:
        cache: gradle
        distribution: temurin
        java-version: 21
    - name: Build with Gradle
      run: ./gradlew testDebugUnitTest
