name: CI

permissions: {}

on:
  pull_request:
  push:
    branches:
      - alpha
      - beta
      - main
      - renovate/**

jobs:
  ci-optimization:
    name: CI optimization
    uses: dargmuesli/github-actions/.github/workflows/ci-optimization.yml@298fae1fbc879585a0fc7dbf34e7dee04a0e6b0b # 5.9.1
    permissions:
      pull-requests: read
  build:
    needs: ci-optimization
    if: needs.ci-optimization.outputs.continue == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Set up JDK
      uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
      with:
        cache: gradle
        distribution: temurin
        java-version: 21
    - name: Build with Gradle
      run: ./gradlew testDebugUnitTest
